### ISSUE TITLE
XDG_CONFIG_HOME unset

### ISSUE THREAD

**Issue by bl0nd** [budlabs/mondo#14]
After a clean install, my `$XDG_CONFIG_HOME` is unset so the `$MONDO_DIR` variable gets set to */mondo* which obviously messes things up a bit.

Apparently `$XDG_CONFIG_HOME` isn't set [automatically](https://wiki.archlinux.org/index.php/XDG_Base_Directory#Specification)? I thought it was... Maybe I did something wrong...

Anyways, maybe a check should be put in like `XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"`.

**Comment by budRich** [comment]
thanks for reporting. I will add defaults to that. I actually just recorded a video for my youtube channel about environment variables, where i use XDG_CONFIG_HOME, and in that video i jokingly say "If you want to be really really, thorough, set a default to this as well" :)

**Comment by budRich** [comment]
latest release #15 fixes this .
