### ISSUE TITLE
v.0.0.1 syntax error near unexpected token

### ISSUE THREAD

**Issue by Flores02** [budlabs/mondo#4]
Hello BudRich,

Sorry to disturb you, I decided to use the old version of mondo you used in your videos because it's easier to at the moment and when I ran the script mondo I got this error:
`mondo: line 291: syntax error near unexpected token `('
mondo: line 291: `  cat "$src" "$MONDO_DIR/mondo-init" <(genxcolors "$src") \'
`

Do you know how I can solve it or if you can?

Thanks :)

**Comment by budRich** [comment]
https://youtu.be/Hyupe3FR2w8

fast forward 24 minutes ;)

i just updated mondo, and have made a new mondo video that will replace the old ones. 

I don't know what is causing that issue you are showing, and will not fix it either, the new versions of mondo is much more stable and easier to maintain, and now with the new tutorial it should be easy to set it up also. 

The link at the top of this is for an upcomming video to my channel. The last 10 minutes i update mondo and read your issue.

The new mondo video will be available in a couple of minutes on the channel.

**Comment by budRich** [comment]
https://youtu.be/flyFguRc53M <- new mondo video!
